### ISSUE TITLE
hi，there is some problem in pci shared line irq map functions

### ISSUE THREAD

**Issue by huyf2018** [tiiuae/tii-sel4-vm#35]
hello,
I have some problem in the code， msg->mr1 is always 0-3，pci INTX；code is here：
https://github.com/tiiuae/tii-sel4-vm/blob/ebc887d3e42bbb8944934682bbc997f6f02e903d/src/libsel4vm_glue.c#L209C70-L209C70

but in pcidev_intx_set，need to map it to virtio device id，code is here：
https://github.com/tiiuae/tii-sel4-vm/blob/ebc887d3e42bbb8944934682bbc997f6f02e903d/src/libsel4vm_glue.c#L243C48-L243C65

in my env，there is only 0-3，when device is bigger than 4， the map is not working！
May I ask if there is anything else that needs to be modified?
best regards to you！

**Comment by elmankku** [comment]
Hi, yes thanks for pointing out.

I'm working on the counterpart in the qemu repository. Unfortunately I'm unable to publish the code before next week.

**Comment by huyf2018** [comment]
ok， thank you for your replay！

**Comment by elmankku** [comment]
@huyf2018 the issue should be fixed by https://github.com/tiiuae/qemu-sel4-virtio/pull/12.

Rebuilding the qemu should fix the issue. Let us know it you're still having problems.

**Comment by huyf2018** [comment]
hi，@elmankku ，I fix it in my env，using static mapping pci pins to device irqs！
when I use this patch，get some question here：
https://github.com/tiiuae/qemu-sel4-virtio/blob/244792c7ff015e767f327712643cf5d90123afaa/hw/intc/sel4_intc.c#L42
this will bigger than 32！
but in sel4，when irq is bigger than sel4，it will be false！
https://github.com/tiiuae/tii-sel4-vm/blob/ebc887d3e42bbb8944934682bbc997f6f02e903d/src/libsel4vm_glue.c#L83

so，I think is your sel4 have some other commits？
